version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - .:/code
    environment:
      REDIS_USERNAME: ''
      REDIS_PASSWORD: "mypasswordd"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
     - redis
  redis:
    image: redis
    command: >
      --requirepass "mypasswordd"