---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 3"  # minute (0 - 59)-hour (0 - 23)-day of the month (1 - 31)-month (1 - 12)-day of the week (0 - 6)

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start minikube
      uses: medyagh/setup-minikube@master
      
    - name: Try the cluster !
      run: kubectl get pods -A

    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t felfel:0.0.1 .
        echo -n "verifying images:"
        docker images        

    - name: Deploy to minikube
      run:
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

    - name: Add permissions to the helm file
      run: |
        export SHELL=/bin/bash
        ls -la
        chmod 700 get_helm.sh

    - name: Install helm
      run: |
        export SHELL=/bin/bash
        ./get_helm.sh
        ls -la

    - name: Add permissions to the deployment script
      run: |
        export SHELL=/bin/bash
        chmod 700 deploy_felfel.sh

    - name: Deploy the helm chart
      continue-on-error: true 
      run: |
        export SHELL=/bin/bash
        ./deploy_felfel.sh
      env:
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    - name: Test service URLs
      continue-on-error: true 
      run: |
        minikube service list
        minikube service myfelfel --url -n felfel
        echo "------------------opening the service------------------"
        curl $(minikube service myfelfel --url -n felfel) --max-time 7  
